baseURL = 'https://kaorit.github.io/'
languageCode = 'ja-jp'
title = 'K-Notes'
theme = ""

[params]
  author = "Kaori"
  description = "Hi, There."
  github = "kaorit"
  twitter = "kaorit"
  url = "https://kaorit.github.io"
  keywords = "blog, google analytics"
  rss = false
  lastmod = false
  userStatusEmoji = "😀"
  favicon = "/images/favicon.png"
  location = "Japan"

[markup]
    [markup.tableOfContents]
    endLevel = 3  #どのレベルまで目次に表示するか (h3)
    startLevel = 2  #どのレベルから目次に表示する（h2)