baseURL = 'https://kaorit.github.io/'
languageCode = 'ja-jp'
title = 'My Notes'
theme = "github-style"

[params]
  author = "Kaori"
  description = "Hi, There."
  github = "kaorit"
  twitter = "kaorit"
  url = "https://kaorit.github.io"
  keywords = "blog, google analytics"
  rss = false
  lastmod = false
  userStatusEmoji = "😀"
  favicon = "/images/favicon.png"
  location = "Japan"

 [frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
